[tool.poetry]
name = "spotify-alarm"
version = "0.1.0"
description = ""
authors = ["lil-sussy <naykeysnet@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
spotipy = "^2.25.1"
python-dotenv = "^1.0.0"
yt-dlp = "^2024.1.0"
python-vlc = "^3.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
